=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xsd/unit/mixed.xsd
<!--
	Copyright 2008 Safris Technologies Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

			http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->

<xs:schema elementFormDefault="qualified"
	targetNamespace="http://xml.safris.org/schema/binding/test/unit/mixed.xsd"
	xmlns="http://xml.safris.org/schema/binding/test/unit/mixed.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="root">
		<xs:sequence>
			<xs:element name="zero" type="zero"/>
			<xs:element name="oneEx" type="oneEx"/>
			<xs:element name="oneRe" type="oneRe"/>
			<xs:element name="two" type="two"/>
			<xs:element name="three" type="three"/>
			<xs:element name="four" type="four"/>
			<xs:element name="five" type="five"/>
			<xs:element name="six" type="six"/>
			<xs:element name="seven" type="seven"/>
			<xs:element name="eight" type="eight"/>
			<xs:element name="ten" type="ten"/>
			<xs:element name="elevenEx" type="elevenEx"/>
			<xs:element name="elevenRe" type="elevenRe"/>
			<xs:element name="twelve" type="twelve"/>
			<xs:element name="thirteen" type="thirteen"/>
			<xs:element name="fourteen" type="fourteen"/>
			<xs:element name="fifteen" type="fifteen"/>
			<xs:element name="sixteen" type="sixteen"/>
			<xs:element name="seventeen" type="seventeen"/>
			<xs:element name="eighteen" type="eighteen"/>
			<xs:element name="twenty" type="twenty"/>
			<xs:element name="twentyOne" type="twentyOne"/>
			<xs:element name="twentyTwo" type="twentyTwo"/>
			<xs:element name="twentyThree" type="twentyThree"/>
			<xs:element name="twentyFour" type="twentyFour"/>
			<xs:element name="twentyFive" type="twentyFive"/>
			<xs:element name="twentySix" type="twentySix"/>
			<xs:element name="twentySeven" type="twentySeven"/>
			<xs:element name="twentyEight" type="twentyEight"/>
			<xs:element name="thirty" type="thirty"/>
			<xs:element name="thirtyOne" type="thirtyOne"/>
			<xs:element name="thirtyTwo" type="thirtyTwo"/>
			<xs:element name="thirtyThree" type="thirtyThree"/>
			<xs:element name="thirtyFour" type="thirtyFour"/>
			<xs:element name="thirtyFive" type="thirtyFive"/>
			<xs:element name="thirtySix" type="thirtySix"/>
			<xs:element name="thirtySeven" type="thirtySeven"/>
			<xs:element name="thirtyEight" type="thirtyEight"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="root" type="root"/>
	
	<xs:complexType name="zero">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	
	<xs:complexType name="oneRe">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="xs:anyType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="oneEx">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="xs:anyType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="two" mixed="true">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	
	<xs:complexType name="three">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:restriction base="xs:anyType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="four" mixed="true">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="xs:anyType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="five" mixed="true">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:restriction base="xs:anyType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="six" mixed="false">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:restriction base="xs:anyType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="seven">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0">
			<xs:element name="inner"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="eight" mixed="true">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0">
			<xs:element name="inner"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ten">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="zero"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="elevenEx">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="oneEx"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="elevenRe">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="oneEx"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twelve">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="two"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirteen">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="three"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="fourteen">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="four"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="fifteen">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="five"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="sixteen">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="six"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="seventeen">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="seven"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="eighteen">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="eight"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twenty">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="ten"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentyOne">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="elevenEx"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentyTwo">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="twelve"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentyThree">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="thirteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentyFour">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="fourteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentyFive">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="fifteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentySix">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="sixteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentySeven">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="seventeen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="twentyEight">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="false">
			<xs:extension base="eighteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirty">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="ten"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtyOne">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="elevenEx"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtyTwo">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="twelve"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtyThree">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="thirteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtyFour">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="fourteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtyFive">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="fifteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtySix">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="sixteen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtySeven">
		<xs:annotation>
			<xs:documentation>NOT mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="seventeen"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="thirtyEight">
		<xs:annotation>
			<xs:documentation>mixed</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="eighteen"/>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xml/unit/mixed.xml
<?xml version="1.0" encoding="UTF-8"?>
<root
	xmlns="http://xml.safris.org/schema/binding/test/unit/mixed.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xml.safris.org/schema/binding/test/unit/mixed.xsd mixed.xsd">
	<zero/>
	<oneEx>mixed</oneEx>
	<oneRe/>
	<two>mixed</two>
	<three>mixed</three>
	<four>mixed</four>
	<five/>
	<six>mixed</six>
	<seven/>
	<eight>mixed</eight>
	<ten/>
	<elevenEx>mixed</elevenEx>
	<elevenRe/>
	<twelve>mixed</twelve>
	<thirteen>mixed</thirteen>
	<fourteen>mixed</fourteen>
	<fifteen/>
	<sixteen>mixed</sixteen>
	<seventeen/>
	<eighteen>mixed</eighteen>
	<twenty/>
	<twentyOne/>
	<twentyTwo>mixed</twentyTwo>
	<twentyThree>mixed</twentyThree>
	<twentyFour>mixed</twentyFour>
	<twentyFive/>
	<twentySix>mixed</twentySix>
	<twentySeven/>
	<twentyEight>mixed</twentyEight>
	<thirty>mixed</thirty>
	<thirtyOne>mixed</thirtyOne>
	<thirtyTwo>mixed</thirtyTwo>
	<thirtyThree>mixed</thirtyThree>
	<thirtyFour>mixed</thirtyFour>
	<thirtyFive>mixed</thirtyFive>
	<thirtySix>mixed</thirtySix>
	<thirtySeven/>
	<thirtyEight>mixed</thirtyEight>
</root>
