=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xsd/unit/order.xsd
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema elementFormDefault="qualified"
  targetNamespace="http://xml.safris.org/schema/binding/test/unit/order.xsd"
  xmlns:or="http://xml.safris.org/schema/binding/test/unit/order.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:complexType name="AType">
    <xs:sequence>
      <xs:element name="innerA" type="xs:string"/>
      <xs:element name="innerB" type="xs:integer"/>
      <xs:choice>
        <xs:element name="innerC" type="xs:byte"/>
        <xs:element name="innerD" type="xs:QName"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="A" type="or:AType"/>
  
  <xs:complexType name="BType">
    <xs:complexContent>
      <xs:extension base="or:AType">
        <xs:sequence>
          <xs:element name="A" type="or:AType"/>
          <xs:element name="innerE" type="xs:boolean"/>
          <xs:element name="innerF" type="xs:float"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="B" type="or:BType"/>
  
  <xs:complexType name="CType">
    <xs:complexContent>
      <xs:extension base="or:BType">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="B" type="or:BType"/>
            <xs:element name="innerA" type="xs:string"/>
            <xs:element name="innerF" type="xs:float"/>
            <xs:element name="innerG" type="xs:double"/>
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="C" type="or:CType"/>
  
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="or:A"/>
        <xs:element ref="or:B"/>
        <xs:element ref="or:C"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xml/unit/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<root
	xmlns="http://xml.safris.org/schema/binding/test/unit/order.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xml.safris.org/schema/binding/test/unit/order.xsd ../../xsd/unit/order.xsd">
	<A>
		<innerA>hello first time</innerA>
		<innerB>1</innerB>
		<innerC>48</innerC>
	</A>
	<B>
		<innerA>hi!!</innerA>
		<innerB>2</innerB>
		<innerC>57</innerC>
		<A>
			<innerA>hello first time</innerA>
			<innerB>1</innerB>
			<innerC>48</innerC>
		</A>
		<innerE>true</innerE>
		<innerF>5.3</innerF>
	</B>
	<C>
		<innerA>yo, what's up!?</innerA>
		<innerB>3</innerB>
		<innerC>52</innerC>
		<A>
			<innerA>hello first time</innerA>
			<innerB>1</innerB>
			<innerC>48</innerC>
		</A>
		<innerE>false</innerE>
		<innerF>4</innerF>
		<B>
			<innerA>hi!!</innerA>
			<innerB>2</innerB>
			<innerC>57</innerC>
			<A>
				<innerA>hello first time</innerA>
				<innerB>1</innerB>
				<innerC>48</innerC>
			</A>
			<innerE>true</innerE>
			<innerF>5.3</innerF>
		</B>
		<innerG>-99</innerG>
		<innerA>again</innerA>
		<innerF>54</innerF>
		<innerF>55</innerF>
		<innerF>56</innerF>
		<innerG>99</innerG>
	</C>
</root>
