=== AlekseyYuryev/java/ide/common/src/main/resources/xsd/starting-points.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:sp="http://ide.safris.org/common/starting-points.xsd"
	targetNamespace="http://ide.safris.org/common/starting-points.xsd">

	<xs:element name="startingPoints">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="startingPoint">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="commandLineArguments" type="xs:string"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="target" type="xs:string"/>
							<xs:element name="vmOtherOptions" type="xs:string"/>
							<xs:element name="workingDir" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== AlekseyYuryev/java/xml/generator/compiler/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<startingPoints
	xmlns="http://ide.safris.org/common/starting-points.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../../ide/common/src/main/resources/xsd/starting-points.xsd">
	<startingPoint>
		<commandLineArguments/>
		<name>DateTimeTest</name>
		<target>org.safris.xml.generator.compiler.runtime.lang.DateTimeTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
	<startingPoint>
		<commandLineArguments/>
		<name>BindingsOptionTest</name>
		<target>org.safris.xml.generator.compiler.runtime.BindingsOptionTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
	<startingPoint>
		<commandLineArguments/>
		<name>ClassLoaderTest</name>
		<target>org.safris.xml.generator.compiler.runtime.ClassLoaderTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
</startingPoints>

=== AlekseyYuryev/java/xml/test/binding/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<startingPoints
  xmlns="http://ide.safris.org/common/starting-points.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../../ide/common/src/main/resources/xsd/starting-points.xsd">
  <startingPoint>
    <commandLineArguments/>
    <name>MixedTest</name>
    <target>org.safris.xml.toolkit.test.binding.MixedTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>ListTest</name>
    <target>org.safris.xml.toolkit.test.binding.ListTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>TypeTest</name>
    <target>org.safris.xml.toolkit.test.binding.TypeTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>RedefineTest</name>
    <target>org.safris.xml.toolkit.test.binding.RedefineTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>UnionTest</name>
    <target>org.safris.xml.toolkit.test.binding.UnionTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>NameTest</name>
    <target>org.safris.xml.toolkit.test.binding.NameTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>OrderTest</name>
    <target>org.safris.xml.toolkit.test.binding.OrderTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>IteratorTest</name>
    <target>org.safris.xml.toolkit.test.binding.IteratorTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
</startingPoints>

=== AlekseyYuryev/java/commons/xml/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<startingPoints
  xmlns="http://ide.safris.org/common/starting-points.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../ide/common/src/main/resources/xsd/starting-points.xsd">
  <startingPoint>
    <commandLineArguments/>
    <name>DayTest</name>
    <target>org.safris.commons.xml.binding.DayTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>MonthTest</name>
    <target>org.safris.commons.xml.binding.MonthTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>MonthDayTest</name>
    <target>org.safris.commons.xml.binding.MonthDayTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>YearTest</name>
    <target>org.safris.commons.xml.binding.YearTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>YearMonthTest</name>
    <target>org.safris.commons.xml.binding.YearMonthTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>DateTest</name>
    <target>org.safris.commons.xml.binding.DateTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>DateTimeTest</name>
    <target>org.safris.commons.xml.binding.DateTimeTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>TimeTest</name>
    <target>org.safris.commons.xml.binding.TimeTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>LanguageTest</name>
    <target>org.safris.commons.xml.binding.LanguageTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>DurationTest</name>
    <target>org.safris.commons.xml.binding.DurationTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>NamespaceBindingTest</name>
    <target>org.safris.commons.xml.NamespaceBindingTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
</startingPoints>

=== AlekseyYuryev/java/xml/sample/binding/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<startingPoints
	xmlns="http://ide.safris.org/common/starting-points.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../../ide/common/src/main/resources/xsd/starting-points.xsd">
	<startingPoint>
		<commandLineArguments/>
		<name>AnyTest</name>
		<target>org.safris.xml.toolkit.sample.binding.AnyTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
	<startingPoint>
		<commandLineArguments/>
		<name>EnumsTest</name>
		<target>org.safris.xml.toolkit.sample.binding.EnumsTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
	<startingPoint>
		<commandLineArguments/>
		<name>SimpleTest</name>
		<target>org.safris.xml.toolkit.sample.binding.SimpleTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
	<startingPoint>
		<commandLineArguments/>
		<name>XsiTypeTest</name>
		<target>org.safris.xml.toolkit.sample.binding.XsiTypeTest</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
</startingPoints>

=== AlekseyYuryev/java/maven/plugin/xml/binding/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<startingPoints
  xmlns="http://ide.safris.org/common/starting-points.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../../../ide/common/src/main/resources/xsd/starting-points.xsd">
  <startingPoint>
    <commandLineArguments>/home/safrsev/Projects/org/safris/trunk/xml/sample/binding/pom.xml</commandLineArguments>
    <name>GeneratorMojo sample/binding/pom.xml</name>
    <target>org.safris.maven.plugin.xml.binding.GeneratorMojo</target>
    <vmOtherOptions/>
    <workingDir>..\sample\binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments>/home/safrsev/Projects/org/safris/trunk/xml/tutorial/binding/pom.xml</commandLineArguments>
    <name>GeneratorMojo tutorial/binding/pom.xml</name>
    <target>org.safris.maven.plugin.xml.binding.GeneratorMojo</target>
    <vmOtherOptions/>
    <workingDir>..\tutorial\binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments>/home/safrsev/Projects/org/safris/trunk/xml/test/binding/pom.xml</commandLineArguments>
    <name>GeneratorMojo test/binding/pom.xml</name>
    <target>org.safris.maven.plugin.xml.binding.GeneratorMojo</target>
    <vmOtherOptions/>
    <workingDir>..\test\binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>ExternalTest</name>
    <target>org.safris.maven.plugin.xml.binding.ExternalTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>InternalTest</name>
    <target>org.safris.maven.plugin.xml.binding.InternalTest</target>
    <vmOtherOptions/>
    <workingDir>binding\</workingDir>
  </startingPoint>
</startingPoints>

=== AlekseyYuryev/java/xml/tutorial/binding/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<startingPoints
	xmlns="http://ide.safris.org/common/starting-points.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../../ide/common/src/main/resources/xsd/starting-points.xsd">
	<startingPoint>
		<commandLineArguments/>
		<name>ParseHowTo</name>
		<target>org.safris.xml.tutorial.binding.invoice.ParseHowTo</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
	<startingPoint>
		<commandLineArguments/>
		<name>MarshalHowTo</name>
		<target>org.safris.xml.tutorial.binding.invoice.MarshalHowTo</target>
		<vmOtherOptions/>
		<workingDir/>
	</startingPoint>
</startingPoints>

=== AlekseyYuryev/java/commons/lang/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2008 Seva Safris
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<startingPoints
  xmlns="http://ide.safris.org/common/starting-points.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../ide/common/src/main/resources/xsd/starting-points.xsd">
  <startingPoint>
    <commandLineArguments/>
    <name>ClassesTest</name>
    <target>org.safris.commons.lang.reflect.ClassesTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>ClassLoaderLocalTest</name>
    <target>org.safris.commons.lang.ClassLoaderLocalTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>NumbersTest</name>
    <target>org.safris.commons.lang.NumbersTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>PackageLoaderTest</name>
    <target>org.safris.commons.lang.PackageLoaderTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>PathsTest</name>
    <target>org.safris.commons.lang.PathsTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>ResourcesTest</name>
    <target>org.safris.commons.lang.ResourcesTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>StringsTest</name>
    <target>org.safris.commons.lang.StringsTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
  <startingPoint>
    <commandLineArguments/>
    <name>SystemsTest</name>
    <target>org.safris.commons.lang.SystemsTest</target>
    <vmOtherOptions/>
    <workingDir/>
  </startingPoint>
</startingPoints>

=== AlekseyYuryev/java/xml/toolkit/binding/starting-points.xml
<?xml version="1.0" encoding="UTF-8"?>
<startingPoints
	xmlns="http://ide.safris.org/common/starting-points.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ide.safris.org/common/starting-points.xsd ../../../ide/common/src/main/resources/xsd/starting-points.xsd">
	<startingPoint>
		<commandLineArguments>-d /home/ssafris/Projects/safris/org/xml/trunk/test/binding/target/generated-sources/xmlbinding /home/ssafris/Projects/safris/org/xml/trunk/test/binding/src/test/resources/xsd/liberty/xenc-schema.xsd</commandLineArguments>
		<name>Generator xenc-schema.xsd</name>
		<target>org.safris.xml.toolkit.binding.Generator</target>
		<vmOtherOptions/>
		<workingDir>..\test\binding\</workingDir>
	</startingPoint>
	<startingPoint>
		<commandLineArguments>-d /home/ssafris/Projects/safris/org/xml/trunk/test/binding/target/generated-sources/xmlbinding /home/ssafris/Projects/safris/org/xml/trunk/test/binding/src/test/resources/xsd/liberty/lib-arch-metadata.xsd</commandLineArguments>
		<name>Generator lib-arch-metadata.xsd</name>
		<target>org.safris.xml.toolkit.binding.Generator</target>
		<vmOtherOptions/>
		<workingDir>..\test\binding\</workingDir>
	</startingPoint>
</startingPoints>
