=== AlekseyYuryev/java/commons/json/src/main/resources/json.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2015 Seva Safris

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<xs:schema
  elementFormDefault="qualified"
  targetNamespace="http://commons.safris.org/json.xsd"
  xmlns:json="http://commons.safris.org/json.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:complexType name="value" abstract="true">
    <xs:sequence minOccurs="0">
      <xs:element name="description" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="array" type="xs:boolean"/>
    <xs:attribute name="required" type="xs:boolean" default="true"/>
    <xs:attribute name="null" type="xs:boolean" default="true"/>
  </xs:complexType>
  
  <xs:complexType name="name" abstract="true">
    <xs:complexContent>
      <xs:extension base="json:value">
        <xs:attribute name="name" type="xs:NCName" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="string">
    <xs:complexContent>
      <xs:extension base="json:name">
        <xs:attribute name="pattern" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="number">
    <xs:complexContent>
      <xs:extension base="json:name"/>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="boolean">
    <xs:complexContent>
      <xs:extension base="json:name"/>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="object">
    <xs:complexContent>
      <xs:extension base="json:value">
        <xs:attribute name="type" type="xs:NCName" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="json">
    <xs:complexType>
      <xs:sequence>
        <xs:sequence minOccurs="0">
          <xs:element name="description" type="xs:string"/>
        </xs:sequence>
        <xs:element name="object" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:sequence minOccurs="0">
                <xs:element name="description" type="xs:string"/>
              </xs:sequence>
              <xs:element name="value" type="json:value"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:NCName" use="required"/>
          </xs:complexType>
          <xs:unique name="uniqueValueName">
            <xs:selector xpath="./json:value"/>
            <xs:field xpath="@name"/>
          </xs:unique>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="bundleName" type="xs:NCName" use="required"/>
    </xs:complexType>
    <xs:key name="keyObjectName">
      <xs:selector xpath="./json:object"/>
      <xs:field xpath="@name"/>
    </xs:key>
    <xs:keyref name="keyrefObjectName" refer="json:keyObjectName">
      <xs:selector xpath="./json:object/json:*"/>
      <xs:field xpath="@type"/>
    </xs:keyref>
  </xs:element>

</xs:schema>

=== AlekseyYuryev/java/test/maven/plugin/json/src/test/resources/json.xml
<?xml version="1.0" encoding="UTF-8"?>
<json
  xmlns="http://commons.safris.org/json.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://commons.safris.org/json.xsd http://commons.safris.org/json.xsd">
  <object name="attachment">
    <value name="filename" xsi:type="string"/>
    <value name="data" xsi:type="string"/>
    <value name="serial" xsi:type="number"/>
  </object>
  <object name="signature">
    <value name="xmldsig" xsi:type="string"/>
    <value name="pub_rsa" xsi:type="string"/>
  </object>
  <object name="message">
    <value name="subject" xsi:type="string"/>
    <value name="imortant" xsi:type="boolean"/>
    <value name="recipients" xsi:type="string" array="true"/>
    <value xsi:type="object" type="attachment" array="true"/>
    <value xsi:type="object" type="signature"/>
  </object>
</json>
