=== AlekseyYuryev/java/xml/tutorial/binding/src/main/resources/xsd/invoice.xsd
<!--
  Copyright Safris Software 2006
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema elementFormDefault="qualified"
  targetNamespace="http://xml.safris.org/tutorial/binding/invoice.xsd"
  xmlns:pv="http://xml.safris.org/tutorial/binding/invoice.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="invoice">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="number" type="xs:positiveInteger"/>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="billingAddress" type="pv:addressType"/>
        <xs:element name="shippingAddress" type="pv:addressType"/>
        <xs:element name="billedItems" type="pv:itemsType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="addressType">
    <xs:all>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="postalCode" type="xs:positiveInteger"/>
      <xs:element name="country" type="xs:string"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="itemsType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="item" type="pv:itemType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="code" type="xs:positiveInteger"/>
      <xs:element name="quantity" type="xs:positiveInteger"/>
      <xs:element name="price" type="pv:positiveDecimal"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="positiveDecimal">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== AlekseyYuryev/java/xml/tutorial/binding/src/main/resources/xml/invoice.xml
<!--
  Copyright Safris Software 2006
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<invoice xmlns="http://xml.safris.org/toolkit/tutorial/binding/beginner/invoice.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xml.safris.org/toolkit/tutorial/binding/beginner/invoice.xsd ../xsd/invoice.xsd">
  <number>1458</number>
  <date>2003-01-07</date>
  <billingAddress>
    <name>Ian Barking</name>
    <address>123 Kennel Street</address>
    <city>Dachshund City</city>
    <postalCode>98765</postalCode>
    <country>US</country>
  </billingAddress>
  <shippingAddress>
    <name>Retail Dept.</name>
    <address>888 Dogbowl Street</address>
    <city>Pet City</city>
    <postalCode>98765</postalCode>
    <country>US</country>
  </shippingAddress>
  <billedItems>
    <item>
      <description>Studded Collar</description>
      <code>45342</code>
      <quantity>10</quantity>
      <price>11.95</price>
    </item>
    <item>
      <description>K9 Pet Coat</description>
      <code>25233</code>
      <quantity>5</quantity>
      <price>25.01</price>
    </item>
  </billedItems>
</invoice>
