=== AlekseyYuryev/java/xml/sample/binding/src/main/resources/xsd/list.xsd
<!--
	Copyright 2008 Safris Technologies Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

			http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->

<xs:schema
	elementFormDefault="qualified"
	targetNamespace="http://xml.safris.org/toolkit/sample/binding/list.xsd"
	xmlns:li="http://xml.safris.org/toolkit/sample/binding/list.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="staffType" abstract="true">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="workDays">
				<xs:simpleType>
					<xs:list>
						<xs:simpleType>
							<xs:restriction base="xs:NCName">
								<xs:enumeration value="mon"/>
								<xs:enumeration value="tue"/>
								<xs:enumeration value="wed"/>
								<xs:enumeration value="thu"/>
								<xs:enumeration value="fri"/>
								<xs:enumeration value="sat"/>
								<xs:enumeration value="sun"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:list>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="employeeType">
		<xs:complexContent>
			<xs:extension base="li:staffType">
				<xs:sequence>
					<xs:element name="position">
						<xs:simpleType>
							<xs:restriction base="xs:NCName">
								<xs:enumeration value="cashier"/>
								<xs:enumeration value="sales"/>
								<xs:enumeration value="reception"/>
								<xs:enumeration value="stockroom"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="vacationDates">
						<xs:simpleType>
							<xs:list itemType="xs:date"/>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>			
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="volunteerType">
		<xs:complexContent>
			<xs:extension base="li:staffType">
				<xs:sequence>
					<xs:element name="breakTimes">
						<xs:simpleType>
							<xs:list itemType="xs:time"/>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="roster">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="employees" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="employee" type="li:employeeType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="volunteers" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="volunteer" type="li:volunteerType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== AlekseyYuryev/java/xml/sample/binding/src/main/resources/xml/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<roster
  xmlns="http://xml.safris.org/toolkit/sample/binding/list.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xml.safris.org/toolkit/sample/binding/list.xsd ../xsd/list.xsd">
  <employees>
    <employee>
      <name>James Woods</name>
      <workDays>mon thu wed thu fri</workDays>
      <position>cashier</position>
      <vacationDates>2008-07-19 2008-08-14 2008-09-01</vacationDates>
    </employee>
    <employee>
      <name>Genevieve Cutts</name>
      <workDays>tue thu sat</workDays>
      <position>reception</position>
      <vacationDates>2008-04-24 2008-09-11</vacationDates>
    </employee>
    <employee>
      <name>Nick Bassil</name>
      <workDays>sun mon tue wed thu</workDays>
      <position>stockroom</position>
      <vacationDates>2008-05-12 2008-06-17 2008-07-07 2008-08-22</vacationDates>
    </employee>
    <employee>
      <name>Travis Cook</name>
      <workDays>mon wed fri sat sun</workDays>
      <position>sales</position>
      <vacationDates>2008-03-13 2008-05-22 2008-07-01 2008-08-15</vacationDates>
    </employee>
  </employees>
  <volunteers>
    <volunteer>
      <name>Ricky Myers</name>
      <workDays>mon wed fri</workDays>
      <breakTimes>10:30:00 12:15:00 14:45:00 16:00:00</breakTimes>
    </volunteer>
    <volunteer>
      <name>Alice Weiss</name>
      <workDays>tue thu sat</workDays>
      <breakTimes>10:00:00 12:00:00 14:15:00 16:30:00</breakTimes>
    </volunteer>
    <volunteer>
      <name>Cathy Hong</name>
      <workDays>mon tue wed fri</workDays>
      <breakTimes>10:15:00 12:15:00 14:30:00 16:45:00</breakTimes>
    </volunteer>
  </volunteers>
</roster>
