=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xsd/xdb.xsd
<!--
  Copyright Safris Software 2006
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema 
  elementFormDefault="qualified"
  targetNamespace="http://xml.safris.org/schema/binding/xdb.xsd" 
  xmlns:xdb="http://xml.safris.org/schema/binding/xdb.xsd" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="columnType" abstract="true">
    <xs:attribute name="name" type="xs:NCName" use="required"/>
    <xs:attribute name="null" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="bit">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="length" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="default">
          <xs:simpleType>
            <xs:restriction base="xs:NCName">
              <xs:pattern value="null|[0|1]*"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="blob">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="length" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="default" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="char">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="length" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="default" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="varchar">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="length" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="default" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="numeric">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="points" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="precision" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="unsigned" type="xs:boolean" default="false"/>
        <xs:attribute name="default" type="xs:float"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="decimal">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="points" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="precision" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="unsigned" type="xs:boolean" default="false"/>
        <xs:attribute name="default" type="xs:float"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="integer">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="precision" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="unsigned" type="xs:boolean" default="false"/>
        <xs:attribute name="default">
          <xs:simpleType>
            <xs:restriction base="xs:NCName">
              <xs:pattern value="null|[0-9]*"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="smallint">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="precision" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="unsigned" type="xs:boolean" default="false"/>
        <xs:attribute name="default" type="xs:short"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="float">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="precision" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="unsigned" type="xs:boolean" default="false"/>
        <xs:attribute name="default" type="xs:float"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="date">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="default" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="time">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="default" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="timestamp">
    <xs:complexContent>
      <xs:extension base="xdb:columnType">
        <xs:attribute name="default" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- TODO: Define INTERVAL -->

  <xs:complexType name="tableType">
    <xs:sequence>
      <xs:element name="column" type="xdb:columnType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="constraints" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="primaryKey" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="column" type="xs:NCName" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="autoIncrement" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="column" type="xs:NCName" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:sequence maxOccurs="unbounded">
              <xs:element name="unique" minOccurs="0">
                <xs:complexType>
                	<xs:attribute name="column" type="xs:NCName" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="index" minOccurs="0">
                <xs:complexType>
                	<xs:all>
                		<xs:element name="columns">
                			<xs:complexType>
                				<xs:sequence maxOccurs="unbounded">
                					<xs:element name="column">
                						<xs:complexType>
                							<xs:attribute name="name" type="xs:NCName" use="required"/>
                						</xs:complexType>
                					</xs:element>
                				</xs:sequence>
                			</xs:complexType>
                			<xs:unique name="uniqueColumnName">
                				<xs:selector xpath="./xdb:column"/>
                				<xs:field xpath="@name"/>
                			</xs:unique>
                		</xs:element>
                	</xs:all>
                	<xs:attribute name="unique" type="xs:boolean" default="false"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="foreignKey" minOccurs="0">
                <xs:annotation>
                	<xs:documentation>There is a great potential to be able to have schema validation on the content entered into this element.
                		However, the XPath implementatin supported by the XMLSchema standard does not allow for the necessary complex XPath
                		queries. Therefore, this element is completely unchecked by schema validation for the validity of its content.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                	<xs:all>
                		<xs:element name="references">
                			<xs:complexType>
                				<xs:attribute name="column" type="xs:NCName"/>
                				<xs:attribute name="table" type="xs:NCName" use="required"/>
                			</xs:complexType>
                		</xs:element>
                	</xs:all>
                	<xs:attribute name="column" type="xs:NCName" use="required"/>
                	<xs:attribute name="onDelete" default="cascade">
                		<xs:simpleType>
                			<xs:restriction base="xs:NCName">
                				<xs:enumeration value="cascade"/>
                				<xs:enumeration value="setnull"/>
                				<xs:enumeration value="restrict"/>
                				<xs:enumeration value="ignore"/>
                			</xs:restriction>
                		</xs:simpleType>
                	</xs:attribute>
                	<xs:attribute name="onUpdate" default="cascade">
                		<xs:simpleType>
                			<xs:restriction base="xs:NCName">
                				<xs:enumeration value="cascade"/>
                				<xs:enumeration value="setnull"/>
                				<xs:enumeration value="restrict"/>
                				<xs:enumeration value="ignore"/>
                			</xs:restriction>
                		</xs:simpleType>
                	</xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="check" minOccurs="0">
                <xs:complexType>
                	<xs:attribute name="condition" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueUniqueColumn">
          <xs:selector xpath="./xdb:unique"/>
          <xs:field xpath="@column"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:NCName" use="required"/>
  </xs:complexType>

  <xs:complexType name="databaseType">
    <xs:sequence>
      <xs:element name="source" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="xdb" type="xs:anyURI" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="table" type="xdb:tableType" minOccurs="0" maxOccurs="unbounded">
        <xs:key name="keyColumnName">
          <xs:selector xpath="./xdb:column"/>
          <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="keyrefColumnName" refer="xdb:keyColumnName">
          <xs:selector xpath="./xdb:constraints/xdb:primaryKey | ./xdb:constraints/xdb:autoIncrement | ./xdb:constraints/xdb:unique | ./xdb:constraints/xdb:foreignKey | ./xdb:constraints/xdb:index/xdb:columns/xdb:column"/>
          <xs:field xpath="@column | @name"/>
        </xs:keyref>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:NCName" use="required"/>
  </xs:complexType>

  <xs:element name="database" type="xdb:databaseType">
    <xs:key name="keyTableName">
      <xs:selector xpath="./xdb:table"/>
      <xs:field xpath="@name"/>
    </xs:key>
    <xs:keyref name="keyrefTableName" refer="xdb:keyTableName">
      <xs:selector xpath="./xdb:table/xdb:constraints/xdb:foreignKey/xdb:references"/>
      <xs:field xpath="@table"/>
    </xs:keyref>
  </xs:element>

</xs:schema>

=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xml/xdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2006 Seva Safris

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<xdb:database xmlns:xdb="http://xml.safris.org/schema/binding/xdb.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xml.safris.org/schema/binding/xdb.xsd ../xsd/xdb.xsd"
  name="test-db">
  
  <xdb:table name="test-table">
    <xdb:column xsi:type="xdb:integer" name="test-column" precision="2"/>
    <xdb:column xsi:type="xdb:integer" name="test-column2" precision="2"/>
    <xdb:constraints>
      <xdb:primaryKey column="test-column"/>
    </xdb:constraints>
  </xdb:table>
  
  <xdb:table name="test-table2">
    <xdb:column xsi:type="xdb:integer" name="test-column" precision="2"/>
    <xdb:column xsi:type="xdb:integer" name="test-column3" precision="2"/>
    <xdb:constraints>
      <xdb:primaryKey column="test-column3"/>
      <xdb:autoIncrement column="test-column3"/>
      <xdb:unique column="test-column"/>
      <xdb:index>
        <xdb:columns>
          <xdb:column name="test-column3"/>
          <xdb:column name="test-column"/>
        </xdb:columns>
      </xdb:index>
      <xdb:foreignKey column="test-column3" onDelete="restrict" onUpdate="ignore">
        <xdb:references table="test-table" column="FIXME"/>
      </xdb:foreignKey>
    </xdb:constraints>
  </xdb:table>
  
  <xdb:table name="test-table3">
    <xdb:column xsi:type="xdb:integer" name="test-column" precision="2"/>
    <xdb:column xsi:type="xdb:integer" name="test-column3" precision="2"/>
    <xdb:constraints>
      <xdb:primaryKey column="test-column3"/>
      <xdb:autoIncrement column="test-column3"/>
      <xdb:index>
        <xdb:columns>
          <xdb:column name="test-column3"/>
          <xdb:column name="test-column"/>
        </xdb:columns>
      </xdb:index>
      <xdb:foreignKey column="test-column">
        <xdb:references table="test-table2" column="FIXME"/>
      </xdb:foreignKey>
    </xdb:constraints>
  </xdb:table>
  
</xdb:database>
