=== AlekseyYuryev/java/commons/expect/src/main/resources/xsd/expect.xsd
<!--
	Copyright 2008 Safris Technologies Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

			http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->

<xs:schema
	elementFormDefault="qualified"
	targetNamespace="http://commons.safris.org/expect.xsd"
	xmlns:ex="http://commons.safris.org/expect.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="script">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="process" type="ex:processType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="processType">
		<xs:sequence>
			<xs:element name="rule" type="ex:ruleType" maxOccurs="unbounded"/>
			<xs:element name="tree">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="node">
							<xs:complexType>
								<xs:attribute name="rule" type="xs:IDREF" use="required"/>
								<xs:attribute name="children" type="xs:IDREFS"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="exec" type="xs:string" use="required"/>
		<xs:attribute name="fork" default="async">
			<xs:simpleType>
				<xs:restriction base="xs:NCName">
					<xs:enumeration value="sync"/>
					<xs:enumeration value="async"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="ruleType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="expect" type="xs:string" use="required"/>
		<xs:attribute name="respond" type="xs:string" use="required"/>
	</xs:complexType>

</xs:schema>

=== AlekseyYuryev/java/commons/expect/src/test/resources/xml/expect.xml
<!--
	Copyright 2010 Safris Technologies Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

			http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->

<ex:script
	xmlns:ex="http://commons.safris.org/expect.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://commons.safris.org/expect.xsd ../../../main/resources/xsd/expect.xsd">
	<ex:process exec="java org.safris.commons.expect.ExpectSimulator ${date}">
		<ex:rule id="r1" expect="Would you like to create a roster\?" respond="Y"/>
		<ex:rule id="r2" expect="What is the name of the person\?" respond="${name}"/>
		<ex:rule id="r3" expect="Is [\$\{\}a-zA-Z]+ an adult or a child\?" respond="${adultOrChild}"/>
		<ex:rule id="r4" expect="Is the person a male or female\?" respond="${maleOrFemale}"/>
		<ex:rule id="r5" expect="Will the [\$\{\}a-zA-Z]+ be attending the bbq\?" respond="${attending}"/>
		<ex:rule id="r6" expect="Is this a boy or a girl\?" respond="${boyOrGirl}"/>
		<ex:rule id="r7" expect="What is \$\{person\}'s age\?" respond="${age}"/>
		<ex:rule id="r8" expect="On what date will you see \$\{person\}\?" respond="${date}"/>
		<ex:rule id="r9" expect="Will \$\{person\} bring stuff to the bbq\?" respond="${bringingStuff}"/>
		<ex:rule id="r10" expect="Will \$\{person\} be drinking\?" respond="${drinking}"/>
		<ex:rule id="r11" expect="Will \$\{person\} neet to be driving\?" respond="${driving}"/>
		<ex:rule id="r12" expect="Will \$\{person\} need a ride\?" respond="${needRide}"/>
		<ex:rule id="r13" expect="Print the roster\?" respond="${printRoster}"/>
		<ex:rule id="r14" expect="Quit\?" respond="Y"/>
		<ex:tree>
			<ex:node rule="r1" children="r2"/>
			<ex:node rule="r2" children="r3"/>
			<ex:node rule="r3" children="r4 r6"/>
			<ex:node rule="r4" children="r5"/>
			<ex:node rule="r6" children="r7"/>
			<ex:node rule="r7" children="r5"/>
			<ex:node rule="r5" children="r2 r8"/>
			<ex:node rule="r8" children="r9"/>
			<ex:node rule="r9" children="r10"/>
			<ex:node rule="r10" children="r11 r13"/>
			<ex:node rule="r11" children="r12 r13"/>
			<ex:node rule="r12" children="r13"/>
			<ex:node rule="r13" children="r2 r14"/>
			<ex:node rule="r14"/>
		</ex:tree>
	</ex:process>
</ex:script>
