=== AlekseyYuryev/java/xml/toolkit/binding/src/main/resources/xsd/manifest.xsd
<!--
  Copyright Safris Software 2006
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema
  elementFormDefault="qualified"
  targetNamespace="http://xml.safris.org/toolkit/binding/manifest.xsd"
  xmlns:mf="http://xml.safris.org/toolkit/binding/manifest.xsd"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="xlink.xsd"/>

  <xs:element name="manifest">
    <xs:complexType>
      <xs:choice>
        <xs:element name="link">
          <xs:complexType>
            <xs:attribute ref="xlink:href" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:sequence>
          <xs:element name="destdir">
            <xs:complexType mixed="true">
              <xs:attribute name="explodeJars" type="xs:boolean" default="false"/>
              <xs:attribute name="overwrite" type="xs:boolean" default="false"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="schemas" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="schema" type="xs:anyURI"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:choice>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== AlekseyYuryev/java/xml/test/binding/src/test/resources/xml/manifest.xml
<manifest
	xmlns="http://xml.safris.org/toolkit/binding/manifest.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xml.safris.org/toolkit/binding/manifest.xsd ../../../../../../toolkit/binding/src/main/resources/xsd/manifest.xsd">
	<destdir explodeJars="true">${project.build.directory}/generated-sources/xmlbinding</destdir>
	<schemas>
		<!--
			<schema>${basedir}/src/test/resources/xsd/XMLSchema.xsd</schema>
		-->
		<schema>${basedir}/src/test/resources/xsd/xml.xsd</schema>

		<schema>${basedir}/src/test/resources/xsd/unit/id.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/order.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/name.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/union.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/substitutionGroup.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/list.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/simpleType.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/attribute.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/type.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/namespace.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/complexType.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/unit/mixed.xsd</schema>
		<!--
			<schema>${basedir}/src/test/resources/xsd/unit/everything.xsd</schema>
		-->
		<schema>${basedir}/src/test/resources/xsd/unit/redefine.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/xhtml/xhtml1-taglib.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/maven-v4_0_0.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/exc-c14n.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/xenc-schema.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/xmldsig-core-schema.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/cs-sstc-schema-assertion-01.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/cs-sstc-schema-protocol-01.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/soap-envelope.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/aol-lib-config.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/lib-id-sis-pp.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/lib-arch-authn-context.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/lib-arch-disco-svc.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/lib-arch-metadata.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/lib-arch-soap-binding.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/liberty/lib-arch-protocols-schema.xsd</schema>

		<!--
			These all define the same namespace, and cannot be built into any specific package.
			Only one of these schemas can be generated! The intention of these schemas must be to
			have them be included into other schemas with no targetNamespace.
		-->

		<schema>${basedir}/src/test/resources/xsd/taglibs/j2ee_1_4.xsd</schema>
		<!--
			<schema>${basedir}/src/test/resources/xsd/taglibs/ejb-jar_2_1.xsd</schema>
			<schema>${basedir}/src/test/resources/xsd/taglibs/web-jsptaglibrary_2_0.xsd</schema>
			<schema>${basedir}/src/test/resources/xsd/taglibs/j2ee_web_services_client_1_1.xsd</schema>
		-->
		<schema>${basedir}/src/test/resources/xsd/safris-game-chess.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/xdb.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/test.xsd</schema>
		<schema>${basedir}/src/test/resources/xsd/test2.xsd</schema>
	</schemas>
</manifest>

=== AlekseyYuryev/java/xml/sample/binding/src/main/resources/xml/manifest.xml
<!--
	Copyright 2008 Safris Technologies Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

			http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->

<manifest
	xmlns="http://xml.safris.org/toolkit/binding/manifest.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xml.safris.org/toolkit/binding/manifest.xsd ../../../../../../toolkit/binding/src/main/resources/xsd/manifest.xsd">
	<destdir explodeJars="true">${project.build.directory}/generated-sources/xmlbinding</destdir>
	<schemas>
		<schema>${basedir}/src/main/resources/xsd/substitutionGroup.xsd</schema>
		<schema>${basedir}/src/main/resources/xsd/xsitype.xsd</schema>
		<schema>${basedir}/src/main/resources/xsd/simple.xsd</schema>
		<schema>${basedir}/src/main/resources/xsd/enums.xsd</schema>
		<schema>${basedir}/src/main/resources/xsd/list.xsd</schema>
		<schema>${basedir}/src/main/resources/xsd/any.xsd</schema>
		<schema>${basedir}/src/main/resources/xsd/id.xsd</schema>
	</schemas>
</manifest>
